//! Schedule auto-configuration module / 定时任务自动配置模块
//!
//! Automatically configures scheduled task functionality.
//! 自动配置定时任务功能。
//!
//! # @Scheduled Method Scanning / @Scheduled 方法扫描
//!
//! This module scans for methods annotated with scheduling configuration
//! (cron, fixed_rate, fixed_delay) and registers them with the TaskScheduler.
//!
//! 此模块扫描带有调度配置（cron、fixed_rate、fixed_delay）的方法，
//! 并将它们注册到 TaskScheduler。
//!
//! # Design / 设计
//!
//! Uses `inventory` crate for compile-time collection of scheduled method
//! descriptors, consistent with the existing bean registration pattern.
//!
//! 使用 `inventory` crate 在编译期收集定时方法描述符，
//! 与现有 Bean 注册模式保持一致。

use std::str::FromStr;
use std::sync::Arc;

use crate::core::{ApplicationContext, AutoConfiguration};

// Re-export schedule types
// 重新导出调度类型
pub use hiver_schedule::{
    DEFAULT_FIXED_RATE_MS, DEFAULT_INITIAL_DELAY_MS, DEFAULT_SCHEDULED_POOL_SIZE, ScheduleType,
    ScheduledTask, TaskScheduler, schedule_fixed_delay, schedule_fixed_rate,
};

// ============================================================================
// ScheduledMethodDescriptor / 定时方法描述符
// ============================================================================

/// Compile-time descriptor for a @Scheduled method, submitted via `inventory::submit!`.
/// 编译期的 @Scheduled 方法描述符，通过 `inventory::submit!` 提交。
///
/// Procedural macros (e.g. `#[scheduled]`) populate this at compile time.
/// 过程宏（如 `#[scheduled]`）在编译期填充此结构。
///
/// # Example (generated by macro) / 示例（由宏生成）
///
/// ```rust,ignore
/// inventory::submit! {
///     ScheduledMethodDescriptor {
///         name: "cleanup_task",
///         schedule_config: ScheduleConfig::FixedRate("5s"),
///         task_fn: || { cleanup() },
///     }
/// }
/// ```
pub struct ScheduledMethodDescriptor {
    /// Method name for logging and identification.
    /// 方法名称，用于日志和标识。
    pub name: &'static str,

    /// Scheduling configuration (cron, fixed_rate, or fixed_delay).
    /// 调度配置（cron、fixed_rate 或 fixed_delay）。
    pub schedule_config: ScheduleConfig,

    /// The task function to execute.
    /// 要执行的任务函数。
    pub task_fn: ScheduledFn,
}

/// Task function type stored in the descriptor.
/// 描述符中存储的任务函数类型。
pub type ScheduledFn = Arc<dyn Fn() + Send + Sync + 'static>;

// Collect all scheduled method descriptors at compile time.
// 在编译期收集所有定时方法描述符。
inventory::collect!(ScheduledMethodDescriptor);

// ============================================================================
// ScheduleConfig / 调度配置
// ============================================================================

/// Scheduling configuration parsed from annotation attributes.
/// 从注解属性解析的调度配置。
///
/// Supports three scheduling modes, matching Spring's @Scheduled:
/// 支持三种调度模式，与 Spring 的 @Scheduled 一致：
///
/// - `Cron`: cron expression, e.g. `"0 0 * * *"`
/// - `FixedRate`: fixed interval from start-to-start, e.g. `"5s"`, `"5000ms"`
/// - `FixedDelay`: fixed delay from end-to-start, e.g. `"10s"`
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScheduleConfig {
    /// Cron expression, e.g. `"0 0 * * *"`.
    /// Cron 表达式。
    Cron(&'static str),

    /// Fixed rate (start-to-start interval), e.g. `"5s"`.
    /// 固定速率（从开始到开始的间隔）。
    FixedRate(&'static str),

    /// Fixed delay (end-to-start delay), e.g. `"10s"`.
    /// 固定延迟（从结束到开始的延迟）。
    FixedDelay(&'static str),
}

// ============================================================================
// DurationParser / 时长解析器
// ============================================================================

/// Parsed duration result with millisecond precision.
/// 解析后的时长结果，精度为毫秒。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ParsedDuration {
    /// Duration in milliseconds.
    /// 时长（毫秒）。
    pub millis: u64,
}

impl ParsedDuration {
    /// Create a new parsed duration from milliseconds.
    /// 从毫秒创建解析后的时长。
    pub fn from_millis(millis: u64) -> Self {
        Self { millis }
    }

    /// Create a new parsed duration from seconds.
    /// 从秒创建解析后的时长。
    pub fn from_secs(secs: u64) -> Self {
        Self {
            millis: secs * 1000,
        }
    }

    /// Create a new parsed duration from minutes.
    /// 从分钟创建解析后的时长。
    pub fn from_mins(mins: u64) -> Self {
        Self {
            millis: mins * 60 * 1000,
        }
    }
}

/// Parse a human-readable duration string into milliseconds.
/// 将人类可读的时长字符串解析为毫秒。
///
/// Supported formats:
/// 支持的格式：
///
/// - `"5000ms"` -> 5000 ms
/// - `"5s"` -> 5000 ms
/// - `"1m"` -> 60000 ms
/// - `"1h"` -> 3600000 ms
/// - `"5000"` -> 5000 ms (bare number treated as ms)
///
/// # Errors / 错误
///
/// Returns an error if the string cannot be parsed.
/// 如果字符串无法解析则返回错误。
pub fn parse_duration(input: &str) -> Result<ParsedDuration, ScheduleScanError> {
    let input = input.trim();

    if input.is_empty() {
        return Err(ScheduleScanError::InvalidConfig {
            detail: "duration string is empty".to_string(),
        });
    }

    // Try unit-suffix parsing first.
    // 首先尝试带单位后缀的解析。
    if input.ends_with("ms") {
        let num_str = &input[..input.len() - 2];
        let num: u64 = num_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidConfig {
                detail: format!("invalid milliseconds value: '{}'", num_str),
            })?;
        return Ok(ParsedDuration::from_millis(num));
    }

    if input.ends_with('s') {
        let num_str = &input[..input.len() - 1];
        let num: u64 = num_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidConfig {
                detail: format!("invalid seconds value: '{}'", num_str),
            })?;
        return Ok(ParsedDuration::from_secs(num));
    }

    if input.ends_with('m') {
        let num_str = &input[..input.len() - 1];
        let num: u64 = num_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidConfig {
                detail: format!("invalid minutes value: '{}'", num_str),
            })?;
        return Ok(ParsedDuration::from_mins(num));
    }

    if input.ends_with('h') {
        let num_str = &input[..input.len() - 1];
        let num: u64 = num_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidConfig {
                detail: format!("invalid hours value: '{}'", num_str),
            })?;
        return Ok(ParsedDuration::from_millis(num * 3600 * 1000));
    }

    // Bare number: treat as milliseconds.
    // 纯数字：当作毫秒处理。
    let num: u64 = input
        .parse()
        .map_err(|_| ScheduleScanError::InvalidConfig {
            detail: format!("invalid duration value: '{}'", input),
        })?;
    Ok(ParsedDuration::from_millis(num))
}

// ============================================================================
// CronExpression / Cron 表达式
// ============================================================================

/// A parsed cron expression.
/// 解析后的 Cron 表达式。
///
/// Supports the standard 5-field format: `minute hour day-of-month month day-of-week`.
/// 支持标准 5 字段格式：`分 时 日 月 星期`。
///
/// | Field / 字段        | Allowed values / 允许值 | Special chars / 特殊字符 |
/// |---------------------|------------------------|------------------------|
/// | Minute / 分         | 0-59                   | * , -                  |
/// | Hour / 时           | 0-23                   | * , -                  |
/// | Day of month / 日   | 1-31                   | * , -                  |
/// | Month / 月          | 1-12                   | * , -                  |
/// | Day of week / 星期  | 0-6 (0=Sun)            | * , -                  |
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CronExpression {
    /// Minute field (0-59).
    /// 分钟字段。
    pub minute: CronField,

    /// Hour field (0-23).
    /// 小时字段。
    pub hour: CronField,

    /// Day of month field (1-31).
    /// 日期字段。
    pub day_of_month: CronField,

    /// Month field (1-12).
    /// 月份字段。
    pub month: CronField,

    /// Day of week field (0-6, 0=Sunday).
    /// 星期字段（0=周日）。
    pub day_of_week: CronField,
}

/// A single cron field representing a set of allowed values.
/// 单个 cron 字段，表示一组允许的值。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CronField {
    /// Wildcard — matches all values (`*`).
    /// 通配符 — 匹配所有值。
    All,

    /// A single specific value.
    /// 一个具体的值。
    Exact(u32),

    /// A range of values (inclusive), e.g. `1-5`.
    /// 值范围（含端点）。
    Range(u32, u32),

    /// A list of discrete values, e.g. `1,3,5`.
    /// 离散值列表。
    List(Vec<u32>),

    /// Step values, e.g. `*/5` or `0-30/5`.
    /// 步进值。
    Step {
        /// Base field (what to step from).
        /// 基础字段。
        base: Box<CronField>,
        /// Step size.
        /// 步长。
        step: u32,
    },
}

impl CronField {
    /// Check if a given value matches this field.
    /// 检查给定值是否匹配此字段。
    pub fn matches(&self, value: u32) -> bool {
        match self {
            CronField::All => true,
            CronField::Exact(v) => *v == value,
            CronField::Range(start, end) => value >= *start && value <= *end,
            CronField::List(values) => values.contains(&value),
            CronField::Step { base, step } => {
                if !base.matches(value) {
                    return false;
                }
                // Check if value aligns with step.
                // 检查值是否与步长对齐。
                match base.as_ref() {
                    CronField::All => value % step == 0,
                    CronField::Range(start, _end) => {
                        if value < *start {
                            return false;
                        }
                        (value - start) % step == 0
                    },
                    _ => true,
                }
            },
        }
    }

    /// Get a reference to the inner base, if this is a Step variant.
    /// 获取内部基础的引用。
    fn as_ref(&self) -> &CronField {
        match self {
            CronField::Step { base, .. } => base,
            other => other,
        }
    }
}

/// Errors that can occur during schedule scanning and configuration.
/// 调度扫描和配置过程中可能出现的错误。
#[derive(Debug)]
pub enum ScheduleScanError {
    /// Invalid cron expression.
    /// 无效的 Cron 表达式。
    InvalidCron {
        /// Detail message.
        /// 详细消息。
        detail: String,
    },

    /// Invalid scheduling configuration.
    /// 无效的调度配置。
    InvalidConfig {
        /// Detail message.
        /// 详细消息。
        detail: String,
    },

    /// Multiple conflicting schedule modes specified.
    /// 指定了多个冲突的调度模式。
    ConflictingModes {
        /// The conflicting mode names.
        /// 冲突的模式名称。
        modes: Vec<&'static str>,
    },
}

impl std::fmt::Display for ScheduleScanError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidCron { detail } => {
                write!(f, "invalid cron expression: {}", detail)
            },
            Self::InvalidConfig { detail } => {
                write!(f, "invalid schedule config: {}", detail)
            },
            Self::ConflictingModes { modes } => {
                write!(f, "conflicting schedule modes: {}", modes.join(", "))
            },
        }
    }
}

impl std::error::Error for ScheduleScanError {}

impl FromStr for CronExpression {
    type Err = ScheduleScanError;

    /// Parse a 5-field cron expression.
    /// 解析 5 字段 cron 表达式。
    ///
    /// Format: `minute hour day_of_month month day_of_week`
    /// 格式：`分 时 日 月 星期`
    ///
    /// Each field supports: `*`, specific values, ranges (`1-5`),
    /// lists (`1,3,5`), and steps (`*/5`, `1-10/2`).
    ///
    /// 每个字段支持：`*`、具体值、范围（`1-5`）、列表（`1,3,5`）和步进（`*/5`、`1-10/2`）。
    fn from_str(input: &str) -> Result<Self, Self::Err> {
        let input = input.trim();
        let fields: Vec<&str> = input.split_whitespace().collect();

        if fields.len() != 5 {
            return Err(ScheduleScanError::InvalidCron {
                detail: format!("expected 5 fields, got {}; expression: '{}'", fields.len(), input),
            });
        }

        Ok(CronExpression {
            minute: parse_cron_field(fields[0], 0, 59, "minute")?,
            hour: parse_cron_field(fields[1], 0, 23, "hour")?,
            day_of_month: parse_cron_field(fields[2], 1, 31, "day_of_month")?,
            month: parse_cron_field(fields[3], 1, 12, "month")?,
            day_of_week: parse_cron_field(fields[4], 0, 6, "day_of_week")?,
        })
    }
}

/// Parse a single cron field.
/// 解析单个 cron 字段。
fn parse_cron_field(
    input: &str,
    min_val: u32,
    max_val: u32,
    field_name: &str,
) -> Result<CronField, ScheduleScanError> {
    let input = input.trim();

    // Handle step syntax: base/step.
    // 处理步进语法：base/step。
    if let Some(slash_pos) = input.find('/') {
        let base_str = &input[..slash_pos];
        let step_str = &input[slash_pos + 1..];

        let step: u32 = step_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidCron {
                detail: format!("invalid step value '{}' in field '{}'", step_str, field_name),
            })?;

        if step == 0 {
            return Err(ScheduleScanError::InvalidCron {
                detail: format!("step value must be > 0 in field '{}'", field_name),
            });
        }

        let base = if base_str == "*" {
            CronField::All
        } else {
            parse_cron_atom(base_str, min_val, max_val, field_name)?
        };

        return Ok(CronField::Step {
            base: Box::new(base),
            step,
        });
    }

    // Handle list syntax: a,b,c.
    // 处理列表语法：a,b,c。
    if input.contains(',') {
        let mut values = Vec::new();
        for part in input.split(',') {
            let v = parse_single_value(part.trim(), min_val, max_val, field_name)?;
            values.push(v);
        }
        return Ok(CronField::List(values));
    }

    parse_cron_atom(input, min_val, max_val, field_name)
}

/// Parse a single cron atom (no commas, no slash).
/// 解析单个 cron 原子（不含逗号和斜杠）。
fn parse_cron_atom(
    input: &str,
    min_val: u32,
    max_val: u32,
    field_name: &str,
) -> Result<CronField, ScheduleScanError> {
    if input == "*" {
        return Ok(CronField::All);
    }

    if let Some(dash_pos) = input.find('-') {
        let start_str = &input[..dash_pos];
        let end_str = &input[dash_pos + 1..];

        let start: u32 = start_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidCron {
                detail: format!("invalid range start '{}' in field '{}'", start_str, field_name),
            })?;

        let end: u32 = end_str
            .parse()
            .map_err(|_| ScheduleScanError::InvalidCron {
                detail: format!("invalid range end '{}' in field '{}'", end_str, field_name),
            })?;

        validate_range(start, end, min_val, max_val, field_name)?;
        return Ok(CronField::Range(start, end));
    }

    let v = parse_single_value(input, min_val, max_val, field_name)?;
    Ok(CronField::Exact(v))
}

/// Parse a single numeric value from a cron field.
/// 从 cron 字段解析单个数值。
fn parse_single_value(
    input: &str,
    min_val: u32,
    max_val: u32,
    field_name: &str,
) -> Result<u32, ScheduleScanError> {
    let v: u32 = input.parse().map_err(|_| ScheduleScanError::InvalidCron {
        detail: format!("invalid value '{}' in field '{}'", input, field_name),
    })?;

    if v < min_val || v > max_val {
        return Err(ScheduleScanError::InvalidCron {
            detail: format!(
                "value {} out of range [{}, {}] in field '{}'",
                v, min_val, max_val, field_name
            ),
        });
    }

    Ok(v)
}

/// Validate that a range is within allowed bounds.
/// 验证范围在允许边界内。
fn validate_range(
    start: u32,
    end: u32,
    min_val: u32,
    max_val: u32,
    field_name: &str,
) -> Result<(), ScheduleScanError> {
    if start > end {
        return Err(ScheduleScanError::InvalidCron {
            detail: format!("range start {} > end {} in field '{}'", start, end, field_name),
        });
    }

    if start < min_val || end > max_val {
        return Err(ScheduleScanError::InvalidCron {
            detail: format!(
                "range [{}..{}] out of bounds [{}, {}] in field '{}'",
                start, end, min_val, max_val, field_name
            ),
        });
    }

    Ok(())
}

// ============================================================================
// ScheduledMethodScanner / 定时方法扫描器
// ============================================================================

/// Scans for @Scheduled methods collected via `inventory` and registers them
/// with the TaskScheduler.
/// 扫描通过 `inventory` 收集的 @Scheduled 方法并将它们注册到 TaskScheduler。
///
/// This is the runtime counterpart to the compile-time `#[scheduled]` macro:
/// each annotated method emits a `ScheduledMethodDescriptor` via `inventory::submit!`,
/// and this scanner collects them during application startup.
///
/// 这是编译期 `#[scheduled]` 宏的运行时对应物：
/// 每个被注解的方法通过 `inventory::submit!` 发出一个 `ScheduledMethodDescriptor`，
/// 此扫描器在应用启动时收集它们。
pub struct ScheduledMethodScanner;

impl ScheduledMethodScanner {
    /// Create a new scanner.
    /// 创建新的扫描器。
    pub fn new() -> Self {
        Self
    }

    /// Scan all registered scheduled method descriptors and convert them
    /// into ScheduledTask instances.
    /// 扫描所有已注册的定时方法描述符并将它们转换为 ScheduledTask 实例。
    ///
    /// Returns a vector of (ScheduledTask, ScheduledFn) pairs ready for
    /// registration with the TaskScheduler.
    /// 返回一组 (ScheduledTask, ScheduledFn) 对，可直接注册到 TaskScheduler。
    pub fn scan(&self) -> Result<Vec<DiscoveredScheduledMethod>, ScheduleScanError> {
        let descriptors: Vec<&ScheduledMethodDescriptor> =
            inventory::iter::<ScheduledMethodDescriptor>.collect();

        let mut discovered = Vec::with_capacity(descriptors.len());

        for descriptor in descriptors {
            tracing::info!(
                "Discovered @Scheduled method: '{}' ({:?})",
                descriptor.name,
                descriptor.schedule_config,
            );

            let task = self.build_task(descriptor)?;
            discovered.push(DiscoveredScheduledMethod {
                task,
                task_fn: descriptor.task_fn.clone(),
            });
        }

        tracing::info!("Discovered {} @Scheduled method(s)", discovered.len());
        Ok(discovered)
    }

    /// Build a ScheduledTask from a descriptor.
    /// 从描述符构建 ScheduledTask。
    fn build_task(
        &self,
        descriptor: &ScheduledMethodDescriptor,
    ) -> Result<ScheduledTask, ScheduleScanError> {
        match &descriptor.schedule_config {
            ScheduleConfig::FixedRate(rate_str) => {
                let duration = parse_duration(rate_str)?;
                Ok(ScheduledTask::fixed_rate(descriptor.name, duration.millis))
            },
            ScheduleConfig::FixedDelay(delay_str) => {
                let duration = parse_duration(delay_str)?;
                Ok(ScheduledTask::fixed_delay(descriptor.name, duration.millis))
            },
            ScheduleConfig::Cron(cron_str) => {
                // Validate the cron expression.
                // 验证 cron 表达式。
                let _expr: CronExpression = cron_str.parse()?;
                Ok(ScheduledTask::cron(descriptor.name, *cron_str))
            },
        }
    }
}

impl Default for ScheduledMethodScanner {
    fn default() -> Self {
        Self::new()
    }
}

/// A discovered scheduled method ready for registration.
/// 一个已发现的、准备注册的定时方法。
pub struct DiscoveredScheduledMethod {
    /// The built scheduled task.
    /// 构建好的定时任务。
    pub task: ScheduledTask,

    /// The function to execute.
    /// 要执行的函数。
    pub task_fn: ScheduledFn,
}

// ============================================================================
// ScheduleAutoConfiguration / 定时任务自动配置
// ============================================================================

/// Schedule auto-configuration.
/// 定时任务自动配置。
///
/// Reference: Spring Boot's `TaskSchedulingAutoConfiguration`.
/// 参考 Spring Boot 的 `TaskSchedulingAutoConfiguration`。
#[derive(Debug)]
pub struct ScheduleAutoConfiguration {
    /// Whether scheduling is enabled.
    /// 是否启用定时任务。
    pub enabled: bool,

    /// Thread pool size.
    /// 线程池大小。
    pub pool_size: usize,
}

impl ScheduleAutoConfiguration {
    /// Create a new schedule auto-configuration.
    /// 创建新的定时任务自动配置。
    pub fn new() -> Self {
        Self {
            enabled: false,
            pool_size: 4,
        }
    }

    /// Create from application context configuration.
    /// 从应用上下文配置创建。
    pub fn from_config(ctx: &ApplicationContext) -> Self {
        Self {
            enabled: ctx
                .get_property("schedule.enabled")
                .and_then(|p| p.parse().ok())
                .unwrap_or(false),
            pool_size: ctx
                .get_property("schedule.pool_size")
                .and_then(|p| p.parse().ok())
                .unwrap_or(4),
        }
    }
}

impl Default for ScheduleAutoConfiguration {
    fn default() -> Self {
        Self::new()
    }
}

impl AutoConfiguration for ScheduleAutoConfiguration {
    fn name(&self) -> &'static str {
        "ScheduleAutoConfiguration"
    }

    fn order(&self) -> i32 {
        100 // After core configurations / 在核心配置之后
    }

    fn condition(&self) -> bool {
        self.enabled
    }

    fn configure(&self, ctx: &mut ApplicationContext) -> anyhow::Result<()> {
        tracing::info!("Configuring Scheduled Tasks (Pool size: {})", self.pool_size);

        // Create and register TaskScheduler.
        // 创建并注册 TaskScheduler。
        let scheduler = TaskScheduler::new();
        ctx.register_bean(scheduler);
        tracing::info!("Registered TaskScheduler bean");

        // Scan for @Scheduled annotated methods.
        // 扫描 @Scheduled 注解的方法。
        let scanner = ScheduledMethodScanner::new();
        match scanner.scan() {
            Ok(discovered) => {
                for method in discovered {
                    tracing::info!(
                        "Registering scheduled task: '{}' ({:?})",
                        method.task.name,
                        method.task.schedule_type,
                    );
                    ctx.register_named_bean(
                        format!("scheduled::{}", method.task.name),
                        method.task,
                    );
                }
            },
            Err(e) => {
                tracing::error!("Failed to scan @Scheduled methods: {}", e);
                return Err(anyhow::anyhow!("Scheduled method scanning failed: {}", e));
            },
        }

        Ok(())
    }
}

// ============================================================================
// Tests / 测试
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // CronExpression parsing tests / Cron 表达式解析测试
    // ========================================================================

    #[test]
    fn test_cron_parse_all_wildcards() {
        let expr: CronExpression = "* * * * *".parse().unwrap();
        assert_eq!(expr.minute, CronField::All);
        assert_eq!(expr.hour, CronField::All);
        assert_eq!(expr.day_of_month, CronField::All);
        assert_eq!(expr.month, CronField::All);
        assert_eq!(expr.day_of_week, CronField::All);
    }

    #[test]
    fn test_cron_parse_exact_values() {
        let expr: CronExpression = "0 12 15 6 1".parse().unwrap();
        assert_eq!(expr.minute, CronField::Exact(0));
        assert_eq!(expr.hour, CronField::Exact(12));
        assert_eq!(expr.day_of_month, CronField::Exact(15));
        assert_eq!(expr.month, CronField::Exact(6));
        assert_eq!(expr.day_of_week, CronField::Exact(1));
    }

    #[test]
    fn test_cron_parse_range() {
        let expr: CronExpression = "1-5 0-23 1-31 1-12 0-6".parse().unwrap();
        assert_eq!(expr.minute, CronField::Range(1, 5));
        assert_eq!(expr.hour, CronField::Range(0, 23));
        assert_eq!(expr.day_of_month, CronField::Range(1, 31));
        assert_eq!(expr.month, CronField::Range(1, 12));
        assert_eq!(expr.day_of_week, CronField::Range(0, 6));
    }

    #[test]
    fn test_cron_parse_list() {
        let expr: CronExpression = "0,15,30,45 * * * *".parse().unwrap();
        assert_eq!(expr.minute, CronField::List(vec![0, 15, 30, 45]));
    }

    #[test]
    fn test_cron_parse_step() {
        let expr: CronExpression = "*/5 * * * *".parse().unwrap();
        assert_eq!(
            expr.minute,
            CronField::Step {
                base: Box::new(CronField::All),
                step: 5,
            }
        );
    }

    #[test]
    fn test_cron_parse_range_with_step() {
        let expr: CronExpression = "0-30/10 * * * *".parse().unwrap();
        assert_eq!(
            expr.minute,
            CronField::Step {
                base: Box::new(CronField::Range(0, 30)),
                step: 10,
            }
        );
    }

    #[test]
    fn test_cron_parse_mixed_expression() {
        // Every 15 minutes, during hours 9-17, on any day, any month, Mon-Fri
        // 每 15 分钟，9-17 点，任意日期，任意月份，周一到周五
        let expr: CronExpression = "*/15 9-17 * * 1-5".parse().unwrap();
        assert_eq!(
            expr.minute,
            CronField::Step {
                base: Box::new(CronField::All),
                step: 15,
            }
        );
        assert_eq!(expr.hour, CronField::Range(9, 17));
        assert_eq!(expr.day_of_month, CronField::All);
        assert_eq!(expr.month, CronField::All);
        assert_eq!(expr.day_of_week, CronField::Range(1, 5));
    }

    #[test]
    fn test_cron_rejects_wrong_field_count() {
        // Too few fields.
        let result = "0 0 * *".parse::<CronExpression>();
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), ScheduleScanError::InvalidCron { .. }));

        // Too many fields.
        let result = "0 0 * * * *".parse::<CronExpression>();
        assert!(result.is_err());
    }

    #[test]
    fn test_cron_rejects_out_of_range_values() {
        // Minute 60 is out of range.
        let result = "60 0 * * *".parse::<CronExpression>();
        assert!(result.is_err());

        // Hour 24 is out of range.
        let result = "0 24 * * *".parse::<CronExpression>();
        assert!(result.is_err());

        // Month 0 is out of range.
        let result = "0 0 * 0 *".parse::<CronExpression>();
        assert!(result.is_err());
    }

    #[test]
    fn test_cron_rejects_inverted_range() {
        let result = "5-1 0 * * *".parse::<CronExpression>();
        assert!(result.is_err());
    }

    #[test]
    fn test_cron_rejects_zero_step() {
        let result = "*/0 0 * * *".parse::<CronExpression>();
        assert!(result.is_err());
    }

    #[test]
    fn test_cron_rejects_non_numeric() {
        let result = "abc 0 * * *".parse::<CronExpression>();
        assert!(result.is_err());
    }

    #[test]
    fn test_cron_empty_string() {
        let result = "".parse::<CronExpression>();
        assert!(result.is_err());
    }

    // ========================================================================
    // CronField::matches tests / CronField 匹配测试
    // ========================================================================

    #[test]
    fn test_cron_field_matches_all() {
        let field = CronField::All;
        assert!(field.matches(0));
        assert!(field.matches(30));
        assert!(field.matches(59));
    }

    #[test]
    fn test_cron_field_matches_exact() {
        let field = CronField::Exact(15);
        assert!(!field.matches(14));
        assert!(field.matches(15));
        assert!(!field.matches(16));
    }

    #[test]
    fn test_cron_field_matches_range() {
        let field = CronField::Range(5, 10);
        assert!(!field.matches(4));
        assert!(field.matches(5));
        assert!(field.matches(7));
        assert!(field.matches(10));
        assert!(!field.matches(11));
    }

    #[test]
    fn test_cron_field_matches_list() {
        let field = CronField::List(vec![1, 5, 10]);
        assert!(field.matches(1));
        assert!(!field.matches(2));
        assert!(field.matches(5));
        assert!(field.matches(10));
        assert!(!field.matches(3));
    }

    #[test]
    fn test_cron_field_matches_step_wildcard() {
        let field = CronField::Step {
            base: Box::new(CronField::All),
            step: 5,
        };
        assert!(field.matches(0));
        assert!(field.matches(5));
        assert!(field.matches(10));
        assert!(field.matches(15));
        assert!(!field.matches(3));
        assert!(!field.matches(7));
    }

    #[test]
    fn test_cron_field_matches_step_range() {
        let field = CronField::Step {
            base: Box::new(CronField::Range(0, 30)),
            step: 10,
        };
        assert!(field.matches(0));
        assert!(field.matches(10));
        assert!(field.matches(20));
        assert!(field.matches(30));
        assert!(!field.matches(5));
        assert!(!field.matches(35));
    }

    // ========================================================================
    // Duration parsing tests / 时长解析测试
    // ========================================================================

    #[test]
    fn test_parse_duration_milliseconds() {
        let d = parse_duration("5000ms").unwrap();
        assert_eq!(d.millis, 5000);
    }

    #[test]
    fn test_parse_duration_seconds() {
        let d = parse_duration("5s").unwrap();
        assert_eq!(d.millis, 5000);
    }

    #[test]
    fn test_parse_duration_minutes() {
        let d = parse_duration("2m").unwrap();
        assert_eq!(d.millis, 120000);
    }

    #[test]
    fn test_parse_duration_hours() {
        let d = parse_duration("1h").unwrap();
        assert_eq!(d.millis, 3600000);
    }

    #[test]
    fn test_parse_duration_bare_number() {
        let d = parse_duration("3000").unwrap();
        assert_eq!(d.millis, 3000);
    }

    #[test]
    fn test_parse_duration_rejects_empty() {
        assert!(parse_duration("").is_err());
    }

    #[test]
    fn test_parse_duration_rejects_invalid() {
        assert!(parse_duration("abc").is_err());
        assert!(parse_duration("abcms").is_err());
        assert!(parse_duration("abcs").is_err());
    }

    #[test]
    fn test_parse_duration_with_whitespace() {
        let d = parse_duration("  5s  ").unwrap();
        assert_eq!(d.millis, 5000);
    }

    #[test]
    fn test_parse_duration_zero() {
        let d = parse_duration("0s").unwrap();
        assert_eq!(d.millis, 0);

        let d = parse_duration("0ms").unwrap();
        assert_eq!(d.millis, 0);
    }

    // ========================================================================
    // ParsedDuration helpers / ParsedDuration 辅助方法测试
    // ========================================================================

    #[test]
    fn test_parsed_duration_from_millis() {
        let d = ParsedDuration::from_millis(100);
        assert_eq!(d.millis, 100);
    }

    #[test]
    fn test_parsed_duration_from_secs() {
        let d = ParsedDuration::from_secs(5);
        assert_eq!(d.millis, 5000);
    }

    #[test]
    fn test_parsed_duration_from_mins() {
        let d = ParsedDuration::from_mins(3);
        assert_eq!(d.millis, 180000);
    }

    // ========================================================================
    // ScheduleConfig tests / ScheduleConfig 测试
    // ========================================================================

    #[test]
    fn test_schedule_config_equality() {
        assert_eq!(ScheduleConfig::FixedRate("5s"), ScheduleConfig::FixedRate("5s"));
        assert_eq!(ScheduleConfig::FixedDelay("10s"), ScheduleConfig::FixedDelay("10s"));
        assert_eq!(ScheduleConfig::Cron("0 0 * * *"), ScheduleConfig::Cron("0 0 * * *"));
    }

    #[test]
    fn test_schedule_config_inequality() {
        assert_ne!(ScheduleConfig::FixedRate("5s"), ScheduleConfig::FixedRate("10s"));
        assert_ne!(ScheduleConfig::FixedRate("5s"), ScheduleConfig::FixedDelay("5s"));
    }

    // ========================================================================
    // ScheduleScanError display tests / ScheduleScanError 显示测试
    // ========================================================================

    #[test]
    fn test_schedule_scan_error_display() {
        let err = ScheduleScanError::InvalidCron {
            detail: "bad expr".to_string(),
        };
        assert!(err.to_string().contains("bad expr"));

        let err = ScheduleScanError::InvalidConfig {
            detail: "bad config".to_string(),
        };
        assert!(err.to_string().contains("bad config"));

        let err = ScheduleScanError::ConflictingModes {
            modes: vec!["cron", "fixed_rate"],
        };
        assert!(err.to_string().contains("cron"));
        assert!(err.to_string().contains("fixed_rate"));
    }

    // ========================================================================
    // ScheduledMethodScanner tests / ScheduledMethodScanner 测试
    // ========================================================================

    #[test]
    fn test_scanner_builds_fixed_rate_task() {
        let scanner = ScheduledMethodScanner::new();
        let descriptor = ScheduledMethodDescriptor {
            name: "test_fixed_rate",
            schedule_config: ScheduleConfig::FixedRate("5s"),
            task_fn: Arc::new(|| {}),
        };

        let task = scanner.build_task(&descriptor).unwrap();
        assert_eq!(task.name, "test_fixed_rate");
        assert!(matches!(task.schedule_type, ScheduleType::FixedRate(_)));
    }

    #[test]
    fn test_scanner_builds_fixed_delay_task() {
        let scanner = ScheduledMethodScanner::new();
        let descriptor = ScheduledMethodDescriptor {
            name: "test_fixed_delay",
            schedule_config: ScheduleConfig::FixedDelay("10s"),
            task_fn: Arc::new(|| {}),
        };

        let task = scanner.build_task(&descriptor).unwrap();
        assert_eq!(task.name, "test_fixed_delay");
        assert!(matches!(task.schedule_type, ScheduleType::FixedDelay(_)));
    }

    #[test]
    fn test_scanner_builds_cron_task() {
        let scanner = ScheduledMethodScanner::new();
        let descriptor = ScheduledMethodDescriptor {
            name: "test_cron",
            schedule_config: ScheduleConfig::Cron("0 0 * * *"),
            task_fn: Arc::new(|| {}),
        };

        let task = scanner.build_task(&descriptor).unwrap();
        assert_eq!(task.name, "test_cron");
        assert!(matches!(task.schedule_type, ScheduleType::Cron(_)));
    }

    #[test]
    fn test_scanner_rejects_invalid_cron() {
        let scanner = ScheduledMethodScanner::new();
        let descriptor = ScheduledMethodDescriptor {
            name: "bad_cron",
            schedule_config: ScheduleConfig::Cron("invalid"),
            task_fn: Arc::new(|| {}),
        };

        let result = scanner.build_task(&descriptor);
        assert!(result.is_err());
    }

    #[test]
    fn test_scanner_rejects_invalid_duration() {
        let scanner = ScheduledMethodScanner::new();
        let descriptor = ScheduledMethodDescriptor {
            name: "bad_duration",
            schedule_config: ScheduleConfig::FixedRate("not_a_duration"),
            task_fn: Arc::new(|| {}),
        };

        let result = scanner.build_task(&descriptor);
        assert!(result.is_err());
    }

    // ========================================================================
    // ScheduleAutoConfiguration tests / 定时任务自动配置测试
    // ========================================================================

    #[test]
    fn test_schedule_auto_config_defaults() {
        let config = ScheduleAutoConfiguration::new();
        assert!(!config.enabled);
        assert_eq!(config.pool_size, 4);
    }

    #[test]
    fn test_schedule_auto_config_default_trait() {
        let config = ScheduleAutoConfiguration::default();
        assert!(!config.enabled);
        assert_eq!(config.pool_size, 4);
    }

    #[test]
    fn test_schedule_auto_config_name_and_order() {
        let config = ScheduleAutoConfiguration::new();
        assert_eq!(config.name(), "ScheduleAutoConfiguration");
        assert_eq!(config.order(), 100);
    }

    #[test]
    fn test_schedule_auto_config_condition() {
        let config = ScheduleAutoConfiguration {
            enabled: true,
            pool_size: 8,
        };
        assert!(config.condition());

        let config = ScheduleAutoConfiguration {
            enabled: false,
            pool_size: 8,
        };
        assert!(!config.condition());
    }

    #[test]
    fn test_schedule_auto_config_registers_scheduler() {
        let config = ScheduleAutoConfiguration {
            enabled: true,
            pool_size: 4,
        };

        let mut ctx = ApplicationContext::new();
        config.configure(&mut ctx).unwrap();

        // Verify TaskScheduler was registered.
        // 验证 TaskScheduler 已注册。
        assert!(ctx.contains_bean::<TaskScheduler>());
    }

    #[test]
    fn test_schedule_auto_config_from_context() {
        let ctx = ApplicationContext::new();
        let config = ScheduleAutoConfiguration::from_config(&ctx);
        // No properties set, so defaults apply.
        assert!(!config.enabled);
        assert_eq!(config.pool_size, 4);
    }

    // ========================================================================
    // Integration: scan discovers inventory items / 集成：扫描发现 inventory 项
    // ========================================================================

    #[test]
    fn test_scan_with_no_registered_methods() {
        // When no methods have been submitted via inventory::submit!,
        // scan should return an empty vec.
        let scanner = ScheduledMethodScanner::new();
        let discovered = scanner.scan().unwrap();
        // No methods submitted in this test binary.
        assert!(discovered.is_empty());
    }
}
