//! Validated JSON extractor — equivalent to Spring's `@Valid @RequestBody`.
//! 验证 JSON 提取器 — 等价于 Spring 的 `@Valid @RequestBody`。

use hiver_http::HttpBody;
use serde::Deserialize;

use crate::{ExtractorError, ExtractorFuture, FromRequest, Json, Request};

/// Validation trait — types with a `validate()` method can auto-validate.
/// 验证 trait — 有 `validate()` 方法的类型可以自动验证。
pub trait Validate
{
    /// Validate this value, returning field errors on failure.
    /// 验证此值，失败时返回字段错误。
    fn validate_fields(&self) -> Result<(), ValidationError>;
}

/// Validation error with field-level detail.
/// 带字段级别详情的验证错误。
#[derive(Debug, Clone)]
pub struct ValidationError
{
    /// Field errors: (field_name, error_message).
    /// 字段错误：(字段名, 错误消息)。
    pub field_errors: Vec<(String, String)>,
}

impl ValidationError
{
    /// Create from field errors.
    /// 从字段错误创建。
    pub fn new(field_errors: Vec<(String, String)>) -> Self
    {
        Self { field_errors }
    }

    /// Create a single field error.
    /// 创建单个字段错误。
    pub fn field(field: impl Into<String>, message: impl Into<String>) -> Self
    {
        Self {
            field_errors: vec![(field.into(), message.into())],
        }
    }
}

impl std::fmt::Display for ValidationError
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result
    {
        for (i, (field, msg)) in self.field_errors.iter().enumerate()
        {
            if i > 0
            {
                write!(f, ", ")?;
            }
            write!(f, "{field}: {msg}")?;
        }
        Ok(())
    }
}

impl std::error::Error for ValidationError {}

/// Validated JSON extractor — `@Valid @RequestBody` equivalent.
/// 验证 JSON 提取器 — 等价于 `@Valid @RequestBody`。
///
/// Wraps `Json<T>` and calls `T::validate_fields()` after deserialization.
/// If validation fails, returns a 400 Bad Request with error details.
///
/// 包装 `Json<T>`，反序列化后调用 `T::validate_fields()`。
/// 验证失败时返回 400 Bad Request 并附带错误详情。
///
/// # Example / 示例
///
/// ```rust,ignore
/// use hiver_extractors::Valid;
/// use hiver_validation_annotations::{NotNull, Size};
/// use serde::Deserialize;
///
/// #[derive(Deserialize)]
/// struct CreateUser {
///     #[NotNull]
///     name: String,
///     #[Size(min = 6, max = 255)]
///     email: String,
/// }
///
/// async fn create_user(Valid(user): Valid<CreateUser>) -> String {
///     format!("Created: {}", user.name)
/// }
/// ```
pub struct Valid<T>(pub T);

impl<T> Valid<T>
{
    /// Consume and get inner value.
    /// 消费并获取内部值。
    pub fn into_inner(self) -> T
    {
        self.0
    }
}

impl<T> std::fmt::Debug for Valid<T>
where
    T: std::fmt::Debug,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result
    {
        f.debug_tuple("Valid").field(&self.0).finish()
    }
}

impl<T> FromRequest for Valid<T>
where
    T: for<'de> Deserialize<'de> + Validate + Send + 'static,
{
    fn from_request(req: &Request) -> ExtractorFuture<Self>
    {
        let body_bytes = req.body().as_bytes().map(<[u8]>::to_vec);
        let content_type = req.header("content-type").unwrap_or("").to_string();

        Box::pin(async move {
            if !content_type.starts_with("application/json")
                && !content_type.starts_with("application/")
                && !content_type.is_empty()
            {
                return Err(ExtractorError::Invalid(format!(
                    "Expected JSON content type, got: {content_type}"
                )));
            }

            let body = body_bytes.ok_or_else(|| {
                ExtractorError::Invalid("Request body is not available".to_string())
            })?;

            // Step 1: Deserialize JSON
            let value: T = serde_json::from_slice(&body)
                .map_err(ExtractorError::from)?;

            // Step 2: Validate
            value.validate_fields().map_err(|e: ValidationError| {
                ExtractorError::Invalid(format!("Validation failed: {e}"))
            })?;

            Ok(Valid(value))
        })
    }
}

/// Blanket impl: types that have a `validate() -> Result<(), String>` method
/// (generated by hiver-validation-annotations derive) also implement Validate.
/// 自动为有 `validate() -> Result<(), String>` 的类型实现 Validate trait。
impl<T: Validate> Valid<T>
{
    /// Create a Valid wrapper, validating the value.
    /// 创建 Valid 包装器，验证值。
    pub fn new(value: T) -> Result<Self, ValidationError>
    {
        value.validate_fields()?;
        Ok(Valid(value))
    }
}
