//! Chat model abstractions for AI/LLM interactions.
//! AI/LLM 交互的聊天模型抽象。
//!
//! This module defines the core types for interacting with chat-based AI models:
//! messages, requests, responses, streaming, and token usage tracking.
//!
//! 本模块定义了与基于聊天的 AI 模型交互的核心类型：
//! 消息、请求、响应、流式传输和 token 使用量跟踪。

use futures::Stream;
use serde::{Deserialize, Serialize};
use std::pin::Pin;

/// The role of a participant in a chat conversation.
/// 聊天对话中参与者的角色。
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Role {
    /// System message providing instructions to the AI.
    /// 系统消息，为 AI 提供指令。
    System,
    /// User message from the end user.
    /// 来自最终用户的用户消息。
    User,
    /// Assistant message generated by the AI model.
    /// AI 模型生成的助手消息。
    Assistant,
    /// Tool message containing the result of a tool execution.
    /// 包含工具执行结果的工具消息。
    Tool,
}

impl Role {
    /// Returns the string representation of the role.
    /// 返回角色的字符串表示。
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
            Role::Tool => "tool",
        }
    }
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A single message in a chat conversation.
/// 聊天对话中的单条消息。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// The role of the message sender.
    /// 消息发送者的角色。
    pub role: Role,
    /// The content of the message.
    /// 消息内容。
    pub content: String,
    /// Optional name identifying the message sender.
    /// 可选的标识消息发送者的名称。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ChatMessage {
    /// Creates a new chat message with the given role and content.
    /// 使用给定角色和内容创建新的聊天消息。
    ///
    /// # Examples / 示例
    ///
    /// ```
    /// use hiver_ai::chat_model::{ChatMessage, Role};
    ///
    /// let msg = ChatMessage::new(Role::User, "Hello!");
    /// assert_eq!(msg.role, Role::User);
    /// assert_eq!(msg.content, "Hello!");
    /// ```
    #[must_use]
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
            name: None,
        }
    }

    /// Creates a new system message.
    /// 创建新的系统消息。
    #[must_use]
    pub fn system(content: impl Into<String>) -> Self {
        Self::new(Role::System, content)
    }

    /// Creates a new user message.
    /// 创建新的用户消息。
    #[must_use]
    pub fn user(content: impl Into<String>) -> Self {
        Self::new(Role::User, content)
    }

    /// Creates a new assistant message.
    /// 创建新的助手消息。
    #[must_use]
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::new(Role::Assistant, content)
    }

    /// Creates a new tool message.
    /// 创建新的工具消息。
    #[must_use]
    pub fn tool(content: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: content.into(),
            name: Some(name.into()),
        }
    }

    /// Sets the optional name of the message sender.
    /// 设置消息发送者的可选名称。
    #[must_use]
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.name = Some(name.into());
        self
    }
}

/// Token usage statistics for an AI model response.
/// AI 模型响应的 token 使用统计。
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TokenUsage {
    /// Number of tokens in the prompt / 提示中的 token 数量。
    pub prompt_tokens: u32,
    /// Number of tokens in the completion / 补全中的 token 数量。
    pub completion_tokens: u32,
    /// Total number of tokens used / 使用的 token 总数。
    pub total_tokens: u32,
}

impl TokenUsage {
    /// Creates a new token usage with the given values.
    /// 使用给定值创建新的 token 使用统计。
    #[must_use]
    pub fn new(prompt_tokens: u32, completion_tokens: u32) -> Self {
        Self {
            prompt_tokens,
            completion_tokens,
            total_tokens: prompt_tokens + completion_tokens,
        }
    }
}

/// A request to a chat model.
/// 对聊天模型的请求。
#[derive(Debug, Clone)]
pub struct ChatRequest {
    /// The messages to send to the model.
    /// 发送给模型的消息列表。
    pub messages: Vec<ChatMessage>,
    /// Sampling temperature (0.0 - 2.0). Higher values produce more random results.
    /// 采样温度 (0.0 - 2.0)，值越高产生越随机的结果。
    pub temperature: Option<f64>,
    /// Maximum number of tokens to generate in the completion.
    /// 补全中生成的最大 token 数量。
    pub max_tokens: Option<u32>,
    /// The model identifier to use for the request.
    /// 请求使用的模型标识符。
    pub model: Option<String>,
}

impl ChatRequest {
    /// Creates a new empty chat request.
    /// 创建新的空聊天请求。
    #[must_use]
    pub fn new() -> Self {
        Self {
            messages: Vec::new(),
            temperature: None,
            max_tokens: None,
            model: None,
        }
    }

    /// Adds a message to the request.
    /// 向请求添加消息。
    #[must_use]
    pub fn message(mut self, message: ChatMessage) -> Self {
        self.messages.push(message);
        self
    }

    /// Sets the sampling temperature.
    /// 设置采样温度。
    #[must_use]
    pub fn temperature(mut self, temperature: f64) -> Self {
        self.temperature = Some(temperature);
        self
    }

    /// Sets the maximum number of tokens.
    /// 设置最大 token 数量。
    #[must_use]
    pub fn max_tokens(mut self, max_tokens: u32) -> Self {
        self.max_tokens = Some(max_tokens);
        self
    }

    /// Sets the model identifier.
    /// 设置模型标识符。
    #[must_use]
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }
}

impl Default for ChatRequest {
    fn default() -> Self {
        Self::new()
    }
}

/// A response from a chat model.
/// 聊天模型的响应。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    /// The generated content of the response.
    /// 响应的生成内容。
    pub content: String,
    /// The model that generated this response.
    /// 生成此响应的模型。
    pub model: String,
    /// Token usage statistics.
    /// Token 使用统计。
    pub usage: TokenUsage,
    /// The reason the model finished generating (e.g., "stop", "length").
    /// 模型停止生成的原因（例如 "stop"、"length"）。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

impl ChatResponse {
    /// Creates a new chat response.
    /// 创建新的聊天响应。
    #[must_use]
    pub fn new(content: impl Into<String>, model: impl Into<String>) -> Self {
        Self {
            content: content.into(),
            model: model.into(),
            usage: TokenUsage::default(),
            finish_reason: None,
        }
    }

    /// Sets the token usage for this response.
    /// 设置此响应的 token 使用统计。
    #[must_use]
    pub fn usage(mut self, usage: TokenUsage) -> Self {
        self.usage = usage;
        self
    }

    /// Sets the finish reason for this response.
    /// 设置此响应的完成原因。
    #[must_use]
    pub fn finish_reason(mut self, reason: impl Into<String>) -> Self {
        self.finish_reason = Some(reason.into());
        self
    }
}

/// A streamed chunk from a chat model.
/// 聊天模型的流式传输块。
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatChunk {
    /// The incremental content of this chunk.
    /// 此块的增量内容。
    pub content: String,
    /// The model generating this chunk.
    /// 生成此块的模型。
    pub model: String,
    /// Whether this is the final chunk.
    /// 是否为最后一个块。
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// A stream of chat chunks from a chat model.
/// 来自聊天模型的聊天块流。
pub type ChatStream = Pin<Box<dyn Stream<Item = Result<ChatChunk, ModelError>> + Send>>;

/// Errors that can occur when interacting with AI models.
/// 与 AI 模型交互时可能发生的错误。
#[derive(Debug, thiserror::Error)]
pub enum ModelError {
    /// An error occurred during the HTTP request to the model API.
    /// 向模型 API 发送 HTTP 请求时发生错误。
    #[error("Request failed: {0}")]
    RequestFailed(String),

    /// The model API returned an error response.
    /// 模型 API 返回错误响应。
    #[error("API error (status {status}): {message}")]
    ApiError {
        /// HTTP status code / HTTP 状态码。
        status: u16,
        /// Error message from the API / API 返回的错误消息。
        message: String,
    },

    /// The response from the model could not be parsed.
    /// 无法解析模型的响应。
    #[error("Failed to parse response: {0}")]
    ParseError(String),

    /// Rate limit exceeded for the model API.
    /// 超过模型 API 的速率限制。
    #[error("Rate limit exceeded, retry after {retry_after_secs}s")]
    RateLimited {
        /// Suggested retry delay in seconds / 建议的重试延迟（秒）。
        retry_after_secs: u64,
    },

    /// The model is not available or the API key is invalid.
    /// 模型不可用或 API 密钥无效。
    #[error("Authentication or model not found: {0}")]
    AuthError(String),

    /// The request timed out.
    /// 请求超时。
    #[error("Request timed out after {timeout_secs}s")]
    Timeout {
        /// Timeout duration in seconds / 超时时间（秒）。
        timeout_secs: u64,
    },

    /// A custom error from a model implementation.
    /// 来自模型实现的自定义错误。
    #[error("{0}")]
    Custom(String),
}

/// Trait for chat model implementations.
/// 聊天模型实现的 trait。
///
/// This trait defines the interface for all chat-based AI models,
/// enabling pluggable backends (OpenAI, Anthropic, local models, etc.).
///
/// 此 trait 定义了所有基于聊天的 AI 模型的接口，
/// 支持可插拔的后端（OpenAI、Anthropic、本地模型等）。
#[async_trait::async_trait]
pub trait ChatModel: Send + Sync {
    /// Sends a chat request and returns a complete response.
    /// 发送聊天请求并返回完整响应。
    async fn complete(&self, request: ChatRequest) -> Result<ChatResponse, ModelError>;

    /// Sends a chat request and returns a stream of response chunks.
    /// 发送聊天请求并返回响应块的流。
    async fn stream(&self, request: ChatRequest) -> Result<ChatStream, ModelError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_role_as_str() {
        assert_eq!(Role::System.as_str(), "system");
        assert_eq!(Role::User.as_str(), "user");
        assert_eq!(Role::Assistant.as_str(), "assistant");
        assert_eq!(Role::Tool.as_str(), "tool");
    }

    #[test]
    fn test_role_display() {
        assert_eq!(Role::User.to_string(), "user");
    }

    #[test]
    fn test_chat_message_constructors() {
        let sys = ChatMessage::system("You are helpful.");
        assert_eq!(sys.role, Role::System);
        assert_eq!(sys.content, "You are helpful.");

        let usr = ChatMessage::user("Hello!");
        assert_eq!(usr.role, Role::User);

        let asst = ChatMessage::assistant("Hi there!");
        assert_eq!(asst.role, Role::Assistant);

        let tool = ChatMessage::tool("result data", "search");
        assert_eq!(tool.role, Role::Tool);
        assert_eq!(tool.name.as_deref(), Some("search"));
    }

    #[test]
    fn test_chat_message_with_name() {
        let msg = ChatMessage::user("Hello").with_name("Alice");
        assert_eq!(msg.name.as_deref(), Some("Alice"));
    }

    #[test]
    fn test_token_usage() {
        let usage = TokenUsage::new(10, 20);
        assert_eq!(usage.prompt_tokens, 10);
        assert_eq!(usage.completion_tokens, 20);
        assert_eq!(usage.total_tokens, 30);
    }

    #[test]
    fn test_chat_request_builder() {
        let req = ChatRequest::new()
            .message(ChatMessage::system("Be brief."))
            .message(ChatMessage::user("What is 2+2?"))
            .temperature(0.7)
            .max_tokens(100)
            .model("gpt-4");

        assert_eq!(req.messages.len(), 2);
        assert_eq!(req.temperature, Some(0.7));
        assert_eq!(req.max_tokens, Some(100));
        assert_eq!(req.model.as_deref(), Some("gpt-4"));
    }

    #[test]
    fn test_chat_request_default() {
        let req = ChatRequest::default();
        assert!(req.messages.is_empty());
        assert!(req.temperature.is_none());
    }

    #[test]
    fn test_chat_response() {
        let resp = ChatResponse::new("Hello!", "gpt-4")
            .usage(TokenUsage::new(5, 2))
            .finish_reason("stop");

        assert_eq!(resp.content, "Hello!");
        assert_eq!(resp.model, "gpt-4");
        assert_eq!(resp.usage.total_tokens, 7);
        assert_eq!(resp.finish_reason.as_deref(), Some("stop"));
    }

    #[test]
    fn test_model_error_display() {
        let err = ModelError::RequestFailed("network error".to_string());
        assert!(err.to_string().contains("network error"));

        let err = ModelError::ApiError {
            status: 429,
            message: "too many requests".to_string(),
        };
        assert!(err.to_string().contains("429"));

        let err = ModelError::RateLimited { retry_after_secs: 30 };
        assert!(err.to_string().contains("30s"));
    }

    #[test]
    fn test_role_serde_roundtrip() {
        let msg = ChatMessage::user("test");
        let json = serde_json::to_string(&msg).expect("serialize");
        let deserialized: ChatMessage = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deserialized.role, Role::User);
        assert_eq!(deserialized.content, "test");
    }
}
